# Generated by Django 5.0.4 on 2024-04-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
